### ISSUE TITLE
About page issues

### ISSUE THREAD

**Issue by truvatech** [greghunt/knowledge#13]
About page pictures right now don't work properly when you click them, but we don't really need the enlarging feature. Pictures could stay as they are.

Also, the email links don't work properly and neither do some of the social media links.

If you don't put the full http:// URl to social media profiles the links send people to a page not found on buildyourwisdom.

**Comment by greghunt** [comment]
Yes, any URLs must be filled in with the full path. So Facebook / Twitter / Google+ must start with an http://
