### ISSUE TITLE
VALHALLA > WISDOM CAMPAIGN PAGE > FAQ section accordion 

### ISSUE THREAD

**Issue by melanieleduc** [greghunt/knowledge#16]
FAQs open on a new page with all kinds of other stuff.... bad UX

Please make an accordion or at least a modal so that the user stays on the same page OR make the FAQs be a link that brings them to a new page with all the FAQs listed there as normal text.

**Comment by greghunt** [comment]
This whole plugin is just bad. Unfortunately, I can't do anything about this without building it from the ground up. I suggest we remove all FAQs and just add them as straight text in the main content box.
