### ISSUE TITLE
VALHALLA > WISDOM CAMPAIGN PAGE > Change title in reward modal 

### ISSUE THREAD

**Issue by melanieleduc** [greghunt/knowledge#17]
Change title from
"Step 1: Specify your contribution amount for The Sustainability Learning Center
to
Your Reward:

**Comment by greghunt** [comment]
I already commented on this, the reward is below in the select box. Wouldn't that be weird repeating it like that?

**Comment by greghunt** [comment]
Spoke with Marc, this is cool it's working properly. For some reason you guys were seeing something else.
