### ISSUE TITLE
WISDOM > SPONSORSHIP PAGE > Help Mel to Format

### ISSUE THREAD

**Issue by melanieleduc** [greghunt/knowledge#25]
Hi Greg, 

I need to make this page: http://buildyourwisdom.com/corporate-sponsorship/ look like the attached mockup. 

What is the best way to proceed? Should I simply code 2 divs with background colors for the content or should you create a structure similar to the DESIGNS template? FYI the learn more links should expand to open a typeform.

Please advise, thanks

![wisdom_corporatesponsorshipa](https://cloud.githubusercontent.com/assets/15948149/11545189/d7369ed8-9913-11e5-9635-ee88cb029013.png)

**Comment by greghunt** [comment]
Copy the HTML markup from the designs page and just change the text:

    <section class="design design--right" style="background-color:#54b4c2">
    <div class="design__gallery">
    <img src="/wp-content/uploads/2015/10/WISDOM_TinyHouse-e1448649630924.png">
    </div>
    <div style="overflow:hidden">
    <h1>THE <strong>TINY HOUSE</strong></h1>
    <p>The most energy efficient Tiny House! With 308 sq. ft. of floor space and a 105 sq. ft. loft, this smart design is optimized for simplicity and comfort.</p>
    </div>
    <button data-btn-expand="" type="button">Learn More</button>
    <div data-more="" class="design__more" style="display:none">
    <button type="button"><i class="fa fa-angle-up"></i></button>
    <ul>
    <li>6’8” x 15’10” sleeping loft and closet</li>
    <li>1 bathroom</li>
    <li>Kitchen supports&nbsp;full-sized appliances</li>
    <li>Flexible main space with high ceiling</li>
    <li>Lots of hidden&nbsp;storage</li>
    </ul>
    <p>Designed with flexibility in mind, the TINY house can be a main dwelling, a guest house, an office or a remote cabin in the woods. TINY delivers a powerful punch in a small space.</p>
    <p>Like all WISDOM&nbsp;homes, TINY meets&nbsp;our stringent environmental requirements for energy performance, healthy materials, fresh and clean interior air, multi-functional design and economy. Our smart Core Unit&nbsp;tucks all the mechanical and service systems into one area, leaving the rest of the spaces free, to be used how you want.</p>
    </div>
    </section>
