### ISSUE TITLE
VALHALLA > WISDOM CAMPAIGN PAGE > Formatting issues

### ISSUE THREAD

**Issue by melanieleduc** [greghunt/knowledge#4]
1. Create new heading class so that headings can match the design mockup
2. Add margin after paragraph and heading tags to create appropriate spacing between content elements
3. In reward modal, replace "Step 1" text with Reward title
4. In reward modal, replace NEXT STEP button with SELECT and make the button green

**Comment by greghunt** [comment]
3) The reward title depends on what's selected below
