### ISSUE TITLE
VALHALLA > WISDOM CAMPAIGN PAGE > Need new data set for rewards (COST value)

### ISSUE THREAD

**Issue by melanieleduc** [greghunt/knowledge#8]
We need a new field in the REWARDS  section backend

We need to record COST value as well as SALE value

This is because some of the rewards cost Valhalla money and this amount must be deducted from the sale price in order to accurately record money raised for the campaing

For example:
Fruit tree cost: $20
Fruit tree sale price: $175
Actual money raised for campaign: $155

If this is possible to code now, it will help avoid accounting headaches in the future.

**Comment by greghunt** [comment]
You guys can't just keep a spreadsheet of costs/reward? It's not a simple thing to customize this plugin, especially when it's so badly coded.

**Comment by ElectricintheForest** [comment]
We will keep track of it elsewhere. You can close this.
