### ISSUE TITLE
Valhalla > Wisdom Campaign Page > Formatting Issues- Sequel

### ISSUE THREAD

**Issue by ElectricintheForest** [greghunt/knowledge#9]
1) The Reward Tiers are Not Ordered Properly
2) The Reward Tiers are not distinguishing between short form response and long form response, making some categories extremely long.

**Comment by greghunt** [comment]
1) There's a sort order input on each reward. Use that. 
2) This is a known trait. Use the long description for all intents and purposes. Any "long" descriptions below on their own page, as per discussion with Marc and Tom.
